export const BACKEND_URL = ""
export const DB_URL = "34.91.40.104"
export const DB_INSTANCE_NAME = "headless-cms-dining-xp"
export const DB_NAME = "directus"
export const BUCKET_NAME = "dining-xp"
export const PROJECT_ID = "headless-cms-350610"
export const CNX_NAME = "headless-cms-350610:europe-west4:headless-cms-dining-xp"
export const DOCKER_IMAGE_URL = "eu.gcr.io/headless-cms-350610/directus:latest"